// Mock data that matches your Express backend structure

export const mockInstitutions = [
  {
    _id: "inst_admin",
    name: "System Administration",
    type: "hospital", // could just be placeholder
    contact: {
      address: "System",
      phone: "System",
      email: "admin@medicalcv.com",
    },
    password: "admin", // ⚠️ plain for mock; hash in DB
    role: "admin",
    services: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    _id: "inst_001",
    name: "City General Hospital",
    type: "hospital",
    contact: {
      address: "123 Medical Center Drive, Downtown, NY 10001",
      phone: "+1-555-0123",
      email: "info@cityhospital.com",
    },
    password: "password123",
    role: "admin_institutions",
    services: [
      "Emergency Care",
      "Surgery",
      "Cardiology",
      "Pediatrics",
      "Radiology",
    ],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
  },
  {
    _id: "inst_002",
    name: "Westside Medical Clinic",
    type: "clinic",
    contact: {
      address: "456 Health Street, Westside, NY 10002",
      phone: "+1-555-0456",
      email: "contact@westsideclinic.com",
    },
    password: "password123",
    role: "admin_institutions",
    services: [
      "General Practice",
      "Immunizations",
      "Lab Tests",
      "Physical Therapy",
    ],
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-20T09:00:00Z",
  },
  {
    _id: "inst_003",
    name: "Children's Healthcare Center",
    type: "hospital",
    contact: {
      address: "789 Kids Avenue, Uptown, NY 10003",
      phone: "+1-555-0789",
      email: "info@childrenshc.com",
    },
    password: "password123",
    role: "admin_institutions",
    services: ["Pediatrics", "NICU", "Pediatric Surgery", "Child Psychology"],
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-01T10:00:00Z",
  },
];

export const mockPatients = [
  {
    patientId: "PAT001",
    name: "John Smith",
    dateOfBirth: "1985-03-15T00:00:00Z",
    gender: "male",
    isPregnant: false,
    bloodType: "O+",
    contact: {
      phone: "+1-555-1001",
      email: "john.smith@email.com",
      address: "123 Oak Street, Anytown, NY 10001",
    },
    emergencyContact: {
      name: "Jane Smith",
      phone: "+1-555-1002",
      relationship: "Spouse",
    },
    allergies: "Penicillin, Shellfish",
    insuranceInfo: {
      type: "private",
      provider: "HealthFirst Insurance",
      policyNumber: "HF123456789",
    },
    institutionIds: ["inst_001"],
    updatedBy: "admin001",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    patientId: "PAT002",
    name: "Maria Garcia",
    dateOfBirth: "1992-07-22T00:00:00Z",
    gender: "female",
    isPregnant: true,
    bloodType: "A+",
    contact: {
      phone: "+1-555-2001",
      email: "maria.garcia@email.com",
      address: "456 Pine Avenue, Somewhere, NY 10002",
    },
    emergencyContact: {
      name: "Carlos Garcia",
      phone: "+1-555-2002",
      relationship: "Husband",
    },
    allergies: "None known",
    insuranceInfo: {
      type: "government",
      provider: "Medicaid",
      policyNumber: "MC987654321",
    },
    institutionIds: ["inst_001", "inst_002"],
    updatedBy: "inst001",
    createdAt: "2024-01-20T14:15:00Z",
    updatedAt: "2024-02-15T09:20:00Z",
  },
  {
    patientId: "PAT003",
    name: "Robert Johnson",
    dateOfBirth: "1978-11-08T00:00:00Z",
    gender: "male",
    isPregnant: false,
    bloodType: "B-",
    contact: {
      phone: "+1-555-3001",
      email: "robert.johnson@email.com",
      address: "789 Elm Drive, Elsewhere, NY 10003",
    },
    emergencyContact: {
      name: "Linda Johnson",
      phone: "+1-555-3002",
      relationship: "Sister",
    },
    allergies: "Latex, Aspirin",
    insuranceInfo: {
      type: "employer",
      provider: "Corporate Health Plan",
      policyNumber: "CHP456789123",
    },
    institutionIds: ["inst_002"],
    updatedBy: "inst001",
    createdAt: "2024-02-01T11:45:00Z",
    updatedAt: "2024-02-01T11:45:00Z",
  },
  {
    patientId: "PAT004",
    name: "Emily Chen",
    dateOfBirth: "2010-05-12T00:00:00Z",
    gender: "female",
    isPregnant: false,
    bloodType: "AB+",
    contact: {
      phone: "+1-555-4001",
      email: "parent@email.com",
      address: "321 Maple Street, Hometown, NY 10004",
    },
    emergencyContact: {
      name: "David Chen",
      phone: "+1-555-4002",
      relationship: "Father",
    },
    allergies: "Peanuts, Tree nuts",
    insuranceInfo: {
      type: "private",
      provider: "Family Care Insurance",
      policyNumber: "FCI789123456",
    },
    institutionIds: ["inst_003"],
    updatedBy: "admin001",
    createdAt: "2024-02-05T16:20:00Z",
    updatedAt: "2024-02-05T16:20:00Z",
  },
];

export const mockDoctors = [
  {
    _id: "doc_001",
    name: "Dr. Michael Thompson",
    email: "m.thompson@cityhospital.com",
    specialization: "Cardiology",
    licenseNumber: "MD123456",
    phone: "+1-555-5001",
    address: "123 Medical Center Drive, Downtown, NY 10001",
    institutionIds: ["inst_001"],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T08:00:00Z",
  },
  {
    _id: "doc_002",
    name: "Dr. Sarah Williams",
    email: "s.williams@westsideclinic.com",
    specialization: "General Practice",
    licenseNumber: "MD234567",
    phone: "+1-555-5002",
    address: "456 Health Street, Westside, NY 10002",
    institutionIds: ["inst_002"],
    createdAt: "2024-01-12T09:30:00Z",
    updatedAt: "2024-01-12T09:30:00Z",
  },
  {
    _id: "doc_003",
    name: "Dr. James Rodriguez",
    email: "j.rodriguez@cityhospital.com",
    specialization: "Emergency Medicine",
    licenseNumber: "MD345678",
    phone: "+1-555-5003",
    address: "123 Medical Center Drive, Downtown, NY 10001",
    institutionIds: ["inst_001"],
    createdAt: "2024-01-15T10:15:00Z",
    updatedAt: "2024-01-15T10:15:00Z",
  },
  {
    _id: "doc_004",
    name: "Dr. Lisa Park",
    email: "l.park@childrenshc.com",
    specialization: "Pediatrics",
    licenseNumber: "MD456789",
    phone: "+1-555-5004",
    address: "789 Kids Avenue, Uptown, NY 10003",
    institutionIds: ["inst_003"],
    createdAt: "2024-01-18T14:20:00Z",
    updatedAt: "2024-01-18T14:20:00Z",
  },
  {
    _id: "doc_005",
    name: "Dr. Ahmed Hassan",
    email: "a.hassan@cityhospital.com",
    specialization: "Surgery",
    licenseNumber: "MD567890",
    phone: "+1-555-5005",
    address: "123 Medical Center Drive, Downtown, NY 10001",
    institutionIds: ["inst_001", "inst_002"],
    createdAt: "2024-01-22T11:10:00Z",
    updatedAt: "2024-01-22T11:10:00Z",
  },
];

export const mockMedicalRecords = [
  {
    _id: "rec_001",
    patientId: "PAT001",
    institutionId: "inst_001",
    doctorId: "doc_001",
    visitInfo: {
      type: "consultation",
      date: "2024-02-15T10:30:00Z",
      isEmergency: false,
    },
    clinicalData: {
      symptoms: "Chest pain, shortness of breath",
      diagnosis: "Mild angina, recommend lifestyle changes",
      treatment: "Prescribed medication, dietary counseling",
      notes: "Patient advised to reduce stress and increase exercise",
    },
    prescriptions: [
      {
        medicationName: "Nitroglycerin",
        dosage: "0.4mg",
        frequency: "As needed",
        duration: "30 days",
        instructions: "Take under tongue for chest pain",
      },
      {
        medicationName: "Atorvastatin",
        dosage: "20mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Take with evening meal",
      },
    ],
    labResults: [
      {
        testName: "Cholesterol Panel",
        result: "Total: 240 mg/dL",
        referenceRange: "< 200 mg/dL",
        status: "abnormal",
      },
      {
        testName: "ECG",
        result: "Normal sinus rhythm",
        referenceRange: "Normal",
        status: "normal",
      },
    ],
    attachments: [],
    createdBy: "inst_001",
    updatedBy: "inst_001",
    createdAt: "2024-02-15T10:30:00Z",
    updatedAt: "2024-02-15T10:30:00Z",
  },
  {
    _id: "rec_002",
    patientId: "PAT002",
    institutionId: "inst_001",
    doctorId: "doc_003",
    visitInfo: {
      type: "emergency",
      date: "2024-02-20T03:15:00Z",
      isEmergency: true,
    },
    clinicalData: {
      symptoms: "Severe abdominal pain, nausea, vomiting",
      diagnosis: "Acute appendicitis",
      treatment: "Emergency appendectomy performed",
      notes: "Surgery successful, patient stable post-op",
    },
    prescriptions: [
      {
        medicationName: "Morphine",
        dosage: "10mg",
        frequency: "Every 4 hours",
        duration: "48 hours",
        instructions: "For post-operative pain management",
      },
      {
        medicationName: "Cefazolin",
        dosage: "1g",
        frequency: "Every 8 hours",
        duration: "5 days",
        instructions: "Antibiotic prophylaxis",
      },
    ],
    labResults: [
      {
        testName: "White Blood Cell Count",
        result: "15,000/μL",
        referenceRange: "4,000-11,000/μL",
        status: "abnormal",
      },
      {
        testName: "CT Scan Abdomen",
        result: "Inflamed appendix confirmed",
        referenceRange: "Normal anatomy",
        status: "abnormal",
      },
    ],
    attachments: [
      {
        fileName: "ct_scan_results.pdf",
        fileUrl: "/attachments/ct_scan_results.pdf",
        fileType: "pdf",
        description: "CT scan showing appendicitis",
      },
    ],
    createdBy: "inst_001",
    updatedBy: "inst_001",
    createdAt: "2024-02-20T03:15:00Z",
    updatedAt: "2024-02-20T03:15:00Z",
  },
  {
    _id: "rec_003",
    patientId: "PAT003",
    institutionId: "inst_002",
    doctorId: "doc_002",
    visitInfo: {
      type: "follow-up",
      date: "2024-02-18T14:00:00Z",
      isEmergency: false,
    },
    clinicalData: {
      symptoms: "Follow-up for hypertension management",
      diagnosis: "Hypertension, well controlled",
      treatment: "Continue current medication regimen",
      notes:
        "Blood pressure readings improved, patient compliant with medication",
    },
    prescriptions: [
      {
        medicationName: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Take in the morning",
      },
    ],
    labResults: [
      {
        testName: "Blood Pressure",
        result: "128/82 mmHg",
        referenceRange: "< 130/80 mmHg",
        status: "normal",
      },
    ],
    attachments: [],
    createdBy: "inst_002",
    updatedBy: "inst_002",
    createdAt: "2024-02-18T14:00:00Z",
    updatedAt: "2024-02-18T14:00:00Z",
  },
  {
    _id: "rec_004",
    patientId: "PAT004",
    institutionId: "inst_003",
    doctorId: "doc_004",
    visitInfo: {
      type: "immunization",
      date: "2024-02-22T11:30:00Z",
      isEmergency: false,
    },
    clinicalData: {
      symptoms: "Routine immunization visit",
      diagnosis: "Healthy child, up to date with vaccinations",
      treatment: "Administered HPV vaccine",
      notes: "No adverse reactions, next appointment in 6 months",
    },
    prescriptions: [],
    labResults: [],
    attachments: [],
    createdBy: "inst_003",
    updatedBy: "inst_003",
    createdAt: "2024-02-22T11:30:00Z",
    updatedAt: "2024-02-22T11:30:00Z",
  },
  {
    _id: "rec_005",
    patientId: "PAT001",
    institutionId: "inst_001",
    doctorId: "doc_005",
    visitInfo: {
      type: "surgery",
      date: "2024-02-25T08:00:00Z",
      admissionDate: "2024-02-25T06:00:00Z",
      dischargeDate: "2024-02-27T10:00:00Z",
      isEmergency: false,
    },
    clinicalData: {
      symptoms: "Scheduled cardiac catheterization",
      diagnosis: "Coronary artery disease, single vessel",
      treatment: "Percutaneous coronary intervention with stent placement",
      notes: "Procedure successful, patient recovering well",
    },
    prescriptions: [
      {
        medicationName: "Clopidogrel",
        dosage: "75mg",
        frequency: "Once daily",
        duration: "365 days",
        instructions: "Take with food to prevent stomach upset",
      },
      {
        medicationName: "Aspirin",
        dosage: "81mg",
        frequency: "Once daily",
        duration: "Indefinitely",
        instructions: "Low-dose aspirin for cardiac protection",
      },
    ],
    labResults: [
      {
        testName: "Cardiac Enzymes",
        result: "Normal",
        referenceRange: "Normal",
        status: "normal",
      },
      {
        testName: "Post-procedure ECG",
        result: "Normal sinus rhythm, no ST changes",
        referenceRange: "Normal",
        status: "normal",
      },
    ],
    attachments: [
      {
        fileName: "catheterization_report.pdf",
        fileUrl: "/attachments/catheterization_report.pdf",
        fileType: "pdf",
        description: "Cardiac catheterization procedure report",
      },
    ],
    createdBy: "inst_001",
    updatedBy: "inst_001",
    createdAt: "2024-02-25T08:00:00Z",
    updatedAt: "2024-02-25T08:00:00Z",
  },
];
